version: '3.8'

services:
  dotfiles-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: dotfiles-test:latest
    container_name: dotfiles-test
    stdin_open: true
    tty: true
    volumes:
      - .:/home/testuser/dotfiles:ro
    working_dir: /home/testuser/dotfiles

