colorscheme everforest

" ========== Plugins {{{1

"call plug#begin('~/.vim/plugged')

"theme
"Plug 'jonathanfilip/vim-lucius'

"focus gained and lost on tmux change window/pane
"Plug 'tmux-plugins/vim-tmux-focus-events'

" better integration with tmux and iterm
"Plug 'wincent/terminus'

" shows how many times a search is present
"Plug 'google/vim-searchindex'

"delete buffers and close them
"Plug 'moll/vim-bbye'

"Plug 'majutsushi/tagbar'
"Plug 'mbbill/undotree'
"Plug 'scrooloose/nerdtree'

"Plug 'roman/golden-ratio'

"Plug '/usr/local/opt/fzf'
"Plug 'junegunn/fzf.vim'
"Plug 'pbogut/fzf-mru.vim'

"Plug 'fatih/vim-go', { 'for': 'go' }

" markdown syntax highlight
"Plug 'tpope/vim-markdown'
"dockerfile syntax highlight
"Plug 'ekalinin/Dockerfile.vim'
"
filetype plugin indent on

" }}}
" ========== Vim Basic Settings
"
syntax on
" Set backup dir for swp files 
set backupdir=~/.vim/backup
set directory=~/.vim/backup

" Basic vim
set nocompatible
set showtabline=1
set cursorline
set novisualbell
set notitle

set virtualedit=block
" autoread if file is changed
set autoread
" don't show the mode
set noshowmode
" show current keypresses
" completion in command mode

" make vim faster
set nocursorcolumn
set scrolloff=5
set scrolljump=5
" don't syntax uber long lines
set synmaxcol=320
set number
set norelativenumber

" Global TAB settings.
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" how backspace works
set backspace=indent,eol,start

" Statusline {{{
if has("statusline")
  set statusline=
  set statusline+=\ \ %n\ \ \ \|
  "set statusline+=\ \ %{WebDevIconsGetFileTypeSymbol()}
  set statusline+=\ %f
  set statusline+=\ %=
  set statusline+=\ %h%m%r%k
  set statusline+=\ %y
  set statusline+=\ %{\"[\".(&fenc==\"\"?&enc:&fenc).((exists(\"+bomb\")\ &&\ &bomb)?\",B\":\"\").\"]\ \"}

  set statusline+=\ %-8.(%l,%c%V%)
  set statusline+=\ %P\ %L\ 
endif

" Change status color on different modes
" First, enable status line always
set laststatus=2

augroup StatusLineGroup
    au!
    au InsertEnter * hi StatusLine guibg=#d0d6dd guifg=#425262 gui=bold
    au InsertLeave * hi StatusLine gui=bold,reverse
augroup END


"}}}
"

" shortmess{{{
set shortmess+=A
set shortmess+=I
set shortmess+=c
set shortmess+=s
set shortmess+=a
"}}}

" list{{{
set list
set listchars=nbsp:⦸,tab:▸\ ,eol:¬,trail:·,precedes:«,extends:»
"}}}

" timeout and fast escape{{{
set timeoutlen=420 ttimeoutlen=10
autocmd CursorMoved * set timeoutlen=420 ttimeoutlen=10
if ! has("gui_running")
    augroup FastEscape
        au!
        au InsertEnter * set timeoutlen=0 ttimeoutlen=0
        au InsertLeave * set timeoutlen=420 ttimeoutlen=10
    augroup END
endif
"}}}

" Search{{{
" Highlight searches
set hlsearch

" Use smartcase
set ignorecase
set smartcase

" Search while typing
set incsearch

let hlstate=0
nnoremap <Leader>n :if (hlstate%2 == 0) \| nohlsearch \| else \| set hlsearch \| endif \| let hlstate=hlstate+1<CR>:echo "toggled visibility for hlsearch"<CR>
inoremap <Leader>n <ESC>:if (hlstate%2 == 0) \|  nohlsearch \| else \| set hlsearch \| endif \| let hlstate=hlstate+1<CR>:echo "toggled visibility for hlsearch"<CR>a}}}


" no and arrows {{{1

" Get Rid of stupid Goddamned help keys
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" Make arrows useless
inoremap <Left> <Nop>
inoremap <Right> <Nop>
inoremap <Up> <Nop>
inoremap <Down> <Nop>
nnoremap <Left> <Nop>
nnoremap <Right> <Nop>
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
vnoremap <Left> <Nop>
vnoremap <Right> <Nop>
vnoremap <Up> <Nop>
vnoremap <Down> <Nop>

" }}}

" return ot last line when reopen {{{
augroup line_return
    au!
    au BufReadPost *
        \ if line("'\"") > 0 && line("'\"") <= line("$") |
        \ execute 'normal! g`"zvzz' |
        \ endif
augroup END"}}}

" =========== Functions ==================

func! ClearTrailingWS()"{{{
  normal! mz
  %s/\s\+$//ge
  normal! `z
endfunc"}}}

func! ShowTrailingWS()"{{{
  match Error /\s\+$/
endfunc"}}}

" =========== Vim Key bindings ==================

" bindings{{{
",w Command to show white space from a file.
nnoremap <leader>w :call ShowTrailingWS()<CR>

",W Command to remove white space from a file.
nnoremap <leader>W :call ClearTrailingWS()<CR>

" Toggle spell
nnoremap <silent> <leader>s :set spell!<CR>

" Make tab in v mode indent code
vnoremap <tab> >gv
vnoremap <s-tab> <gv

" relative numbers key bindings."
nmap <silent> <leader>l <ESC>:set relativenumber!<CR>

" Map ; to : in normal and visual mode.
nnoremap ; :
vnoremap ; :

" let left and right keys go to the next line
set whichwrap+=<,>,h,l

" ,v Select just pasted text.
nnoremap <leader>v V`]

" Search the word under the cursor with Ag/fzf
nnoremap <leader>f mM:Ag! <C-R><C-W><CR>
vnoremap <leader>f mM"hy:Ag! <C-R>h<CR>

" Mapping to Undotree
nmap <C-u> <ESC>:UndotreeToggle<CR>

" Mapping to NvimTree
nnoremap <BS> :NvimTreeToggle %<cr>

" I am not using U anyway, so let's make it Redo.
nnoremap U :redo<CR>

" git
nnoremap ge :GitGutterSignsToggle<CR>
nnoremap gp :GitGutterPreviewHunk<CR>
nnoremap gs :GitGutterStageHunk<CR>
nnoremap gu :GitGutterUndoHunk<CR>
nnoremap gr :GitGutterRevertHunk<CR>
nnoremap gd :Gdiff<CR>
nnoremap gc :Gcommit<CR>
nnoremap [g :GitGutterPrevHunk<CR>
nnoremap ]g :GitGutterNextHunk<CR>

" fzf
nnoremap <tab> :Files<CR>
nnoremap <s-Tab> :FZFMru<CR>
nnoremap <C-b> :Buffers<CR>
nnoremap ` :Tags<CR>
nnoremap \ :TagbarToggle<CR>

" Ctrl+S to save
nnoremap <C-s> :w<CR>
inoremap <C-s> <ESC>:w<CR>
vnoremap <C-s> <ESC>:w<CR>

"}}}

" ========== Splits/Windows {{{1

" Resize Split When the window is resized"
augroup ResizeGroup
  au!
  au VimResized * :wincmd =
augroup END

" Create splits
nnoremap – :split<CR>
nnoremap ≠ :vsplit<CR>

" Navigation between splits
nnoremap <silent> ˚ :wincmd k<CR>
nnoremap <silent> ∆ :wincmd j<CR>
nnoremap <silent> ˙ :wincmd h<CR>
nnoremap <silent> ¬ :wincmd l<CR>
nnoremap <silent> œ :close<CR>

nnoremap <silent>  :res +5<CR>
nnoremap <silent> Ô :res -5<CR>
nnoremap <silent> Ó :vertical resize -5<CR>
nnoremap <silent> Ò :vertical resize +5<CR>

set fillchars=vert:┃
set splitbelow
" }}}

" ========== Buffers {{{1
set hidden
set switchbuf=usetab

" <leader><leader> to toggle between buffers
nmap <leader><leader> <C-^>
vmap <leader><leader> <C-^>

" Navigate splits
nnoremap <silent> <C-l> :bnext<CR>
nnoremap <silent> <C-h> :bprevious<CR>
nnoremap <silent> <C-q> :Bdelete<CR>

" }}}

" ========== Tabs {{{
nnoremap ,to :tabnew %<CR>
nnoremap ,tq :tabclose<CR>

" Navigation in between tabs
nnoremap [t :tabprevious<cr>
nnoremap ]t :tabnext<cr>
""}}}


function! GetBufferList()
  redir =>buflist
  silent! ls!
  redir END
  return buflist
endfunction

function! ToggleList(bufname, pfx)
  let buflist = GetBufferList()
  for bufnum in map(filter(split(buflist, '\n'), 'v:val =~ "'.a:bufname.'"'), 'str2nr(matchstr(v:val, "\\d\\+"))')
    if bufwinnr(bufnum) != -1
      exec(a:pfx.'close')
      return
    endif
  endfor
  if a:pfx == 'l' && len(getloclist(0)) == 0
      echohl ErrorMsg
      echo "Location List is Empty."
      return
  endif
  let winnr = winnr()
  exec(a:pfx.'open')
  if winnr() != winnr
    wincmd p
  endif
endfunction



" ========== Quickfix / Locallist / f<char> navigation{{{
" Quicklist navigation
nnoremap [q :cprev<CR>
nnoremap ]q :cnext<CR>
nnoremap ,q :call ToggleList("Quickfix List", "c")<CR>


" Locallist navigation
nnoremap [a :lprev<CR>
nnoremap ]a :lnext<CR>
nnoremap ,a :call ToggleList("Location List", "l")<CR>
nnoremap ,aa :lfirst <CR>

" Better navigation in jumplist
nnoremap [w <C-o>
nnoremap ]w <C-i>

" Better navigation between results with f<char>
nnoremap [f ,
nnoremap ]f ;

"}}}

" vimrc edit and source {{{1

" Source the vimrc file after saving it
autocmd bufwritepost .vimrc source ~/.vimrc

" Shortcut to edit .vimrc file on the fly on a vertical window.
nnoremap <leader>ev <C-w><C-v><C-l>:e ~/.vimrc<cr>

"}}}

" ========== Plugins Settings =========="

" misc {{{
let g:vim_g_f_command = "Gf"
"let g:deoplete#enable_at_startup = 1
" }}}

"  GitGutter Params {{{1
let g:gitgutter_sign_added = '+'
let g:gitgutter_sign_modified = '~'
let g:gitgutter_sign_removed = '-'
let g:gitgutter_sign_removed_first_line = '–'
let g:gitgutter_sign_modified_removed = '_'
" }}}

" GolderRatio {{{
let g:golden_ratio_exclude_nonmodifiable = 1
let g:golden_ratio_autocommand = 0
" }}}

" Go stuff
nnoremap <leader>gd :GoDef <CR>

"nvim tree find
nnoremap <leader>nf :NvimTreeFindFileToggle <CR>

" fzf {{{
let g:fzf_mru_relative = 1
let g:fzf_tags_command = "ctags -R --exclude=@.ignore --exclude=@.ctagsadditionalignore "
let g:fzf_layout = { 'down': '~23%'  }
function! s:build_quickfix_list(lines)
  call setqflist(map(copy(a:lines), '{ "filename": v:val }'))
  copen
  cc
endfunction

let g:fzf_action = {
  \ 'ctrl-b': function('s:build_quickfix_list'),
  \ 'ctrl-t': 'tab split',
  \ 'ctrl-x': 'split',
  \ 'ctrl-v': 'vsplit' }


command! -bang -nargs=* Ag
  \ call fzf#vim#ag(<q-args>,
  \                 <bang>0 ? fzf#vim#with_preview('up:60%')
  \                         : fzf#vim#with_preview('right:50%:hidden', '?'),
  \                 <bang>0)

"}}}

" supertab {{{
"let g:SuperTabDefaultCompletionType = "<c-n>"
"let g:SuperTabContextDefaultCompletionType = "<c-n>"
"}}}

au FileType javascript setl sw=2 sts=2 et
au FileType vue setl sw=2 sts=2 et
au FileType typescript setl sw=2 sts=2 et
au FileType typescriptreact setl sw=2 sts=2 et
au FileType html setl sw=2 sts=2 et
autocmd FileType vue syntax sync fromstart

autocmd WinLeave * set nocursorline
autocmd WinEnter * set cursorline


function! IPhpInsertUse()
    call PhpInsertUse()
    call feedkeys('a',  'n')
endfunction

autocmd FileType php inoremap <Leader>u <Esc>:call IPhpInsertUse()<CR>
autocmd FileType php noremap <Leader>u :call PhpInsertUse()<CR>

let g:rooter_patterns = ['composer.json', 'go.mod', '.git/']

" Put this in your .vimrc and whenever you `git commit` you'll see the diff of your commit next to your commit message.
" For the most accurate diffs, use `git config --global commit.verbose true`

" BufRead seems more appropriate here but for some reason the final `wincmd p` doesn't work if we do that.
autocmd VimEnter COMMIT_EDITMSG call OpenCommitMessageDiff()
function! OpenCommitMessageDiff()
  " Save the contents of the z register
  let old_z = getreg("z")
  let old_z_type = getregtype("z")

  try
    call cursor(1, 0)
    let diff_start = search("^diff --git")
    if diff_start == 0
      " There's no diff in the commit message; generate our own.
      let @z = system("git diff --cached -M -C")
    else
      " Yank diff from the bottom of the commit message into the z register
      :.,$yank z
      call cursor(1, 0)
    endif

    " Paste into a new buffer
    vnew
    normal! V"zP
  finally
    " Restore the z register
    call setreg("z", old_z, old_z_type)
  endtry

  " Configure the buffer
  set filetype=diff noswapfile nomodified readonly
  silent file [Changes\ to\ be\ committed]

  " Get back to the commit message
  wincmd p
endfunction

autocmd Filetype gitcommit setlocal spell textwidth=72

vnoremap <leader>tf :GoTestFunc <CR>
vnoremap <leader>t :GoTest <CR>
nnoremap <leader>tf :GoTestFunc <CR>
nnoremap <leader>t :GoTest <CR>

" vim:fen:fdm=marker:fmr={{{,}}}:fdl=1:fdc=1:ts=2:sw=2:sts=2
"

let g:go_fmt_command = "goimports"

set so=15
set colorcolumn=100
set completeopt=longest,menuone
